---
title: "Immigration-Analysis-Final"
author: "Chaira Harder, Isabelle Elder, Sirohi Kumar"
format: pdf
editor: visual
---

# An Analysis of Education and Demographic Information on Successful US-Immigration

```{r}

library(dplyr)
library(ggplot2)
library(tidyverse)
library(tidytuesdayR)
library(corrplot)
library(MASS)
library(car)
# library(equatiomatic)

```

## INTRODUCTION

## METHODS

### Load the data:

```{r}
# NOTE: To load data, you must download both the extract's data and the DDI
# and also set the working directory to the folder with these files (or change the path below).

if (!require("ipumsr")) stop("Reading IPUMS data into R requires the ipumsr package. It can be installed using the following command: install.packages('ipumsr')")

ddi <- read_ipums_ddi("highered_00002.xml")
data <- read_ipums_micro(ddi)
```

Wrangling:
```{r}
# remove identifier variables
data <- data |>
  dplyr::select(-PERSONID, -YEAR, -SAMPLE, -SURID, -BTHUS, -NDGMEMG, -CTZUSIN)
```

```{r}
# reconstruct the CTZUS variable to be binary.
# for CTZUS == 3, we will make that 1, and all other categories will be 0
data$CTZUS <- ifelse(data$CTZUS == 3, 1, ifelse(data$CTZUS == 98, NA, 0))

data$CHTOT[data$CHTOT == 98] <- NA

dim(data)
```


```{r}
# remove NA values
data = data |>
  dplyr::filter(!is.na(CTZUS))

dim(data)
```


```{r}
# make our model

simpleModel = glm(CTZUS ~ DGRDG + LFSTAT + CHTOT, data = data, family = binomial)
summary(simpleModel)
vif(simpleModel)
```

```{r}
# make our model

complexModel = glm(CTZUS ~ (DGRDG + LFSTAT + CHTOT) * (RACETH + GENDER), data = data, family = binomial)
summary(complexModel)
vif(complexModel)
```








```{r}
# make all variables characters from ints
data[] <- lapply(data, as.character)
data$CTZUS <- as.numeric(data$CTZUS)
```

```{r}
# MODEL SELECTION

empty_model <- glm(
  CTZUS ~ 1,
  data = data,
  family = binomial
)

head(data)
```

```{r}

full_model <- glm(
  CTZUS ~ GENDER + RACETH + CHTOT + DGRDG + NDGMEMG + LFSTAT,
  data = data,
  family=binomial
)

```

```{r}
stepAIC(
  object = empty_model,
  scope = list(lower = empty_model, upper = full_model),
  direction = "forward",
  test = "F",
  k = 2*qchisq(.95, df = 1)
)
```










```{r}
#delete this

count <- sum(data$CTZUS == 1)
print(count)

# print(names(data))
# sapply(data, class)

# look at distribution of majors

# correlation matrix
numeric_data <- data[, c("GENDER", "RACETH", "BTHUS", "CTZUSIN", "CTZUS", "CHTOT", "DGRDG", "NDGMEMG", "LFSTAT")]

# compute matrix
correlation_matrix <- cor(numeric_data, use = "complete.obs") 
print(correlation_matrix)
```

```{r}
glm(CTZUS ~ . , data = data, family=binomial) |>
  step(direction = "backward", trace = 0) |>
  summary()
```

```{r}
lm(CTZUS ~ . , data = data) |>
  step(direction = "backward", trace = 0) |>
  summary()
```

```{r}

```

### Data wrangling:

```{r}

```

```{r}

```

## RESULTS

### HYPOTHESIS

## DISCUSSION

### LIMITATIONS

### FUTURE DIRECTION

## Data Appendix

#### IPUMS Citation

. Minnesota Population Center. IPUMS Higher Ed: Version 1.0 \[ImmigrationData\]. Minneapolis, MN: University of Minnesota, 2016. https://doi.org/10.18128/D100.V1.0
